---
server:
  port: 7001
  
spring:
    profiles: test
    application:
        name: microservicecloud-config-client-eureka1
        
---
server:
  port: 7004
  
spring:
    profiles: dev
    application:
        name: microservicecloud-config-client-eureka2

---









