---
server:
  port: 8001
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/yingfandb              # 数据库名称

---
server:
  port: 8022
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/yingfandb2              # 数据库名称
---
